@startuml .
!theme syrinx_hybrid from /themes
abstract class AbstractList
abstract AbstractCollection
package stuff {
interface List
interface Collection
}
List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

annotation SuppressWarnings
@enduml